function plot_CaMK2aCost(costDen, costSom)

% author: CORNELIUS BERGMANN
%
% modified 01.06.2022
%
% Input: 
% strats   - matrix containing all strategy parameters
% xval     - array with points along [0, L] where mRNA and protein
%            distibutions were evaluated and will be plotted
% distr_p  - matrix containing protein distributions
% costDat  - matrix containing metabolic costs (transport, translation,
%            transcription, total)
%
% Output: 
%   - 
%--------------------------------------------------
%
% This function plots distributions derived from the equation system 
% detailed in "get_distribution_linDendr".
%
% The plots show
%
% - the protein distributions
% - the resulting metabolic cost

%% initialise figure

figure('FileName', [char(datetime('today', 'Format', 'yyyy_MM_dd')), '_CaMK2aCost'], ...
       'Name'    , 'CaMK2aCost', ...
       'Units'   , 'centimeter', ...
       'Position', [2, 2, 5, 5]);
    
% load colors
load('3Reds4Blues4Greens3Greys3Violets.mat');
% medium dark grey
MediumDarkGrey   = (2.*colors.DarkGrey + [1, 1, 1])./3;

% cost labels, from bottom to top
costLabels       = {'Total \Sigma ', 'Transp. ', 'Transl. ', 'Transcr. '};

%% plot metabolic cost

% major axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [1.5, 0.5, 3, 3], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'FontSize'            , 10, ...
          'FontName'            , 'Arial', ...
          'LineWidth'           , 0.5, ...
          'TickDir'             , 'out', ...
          'TickLabelInterpreter', 'tex', ...
          'TickLength'          , [0.03, 0.01], ...
          'GridColor'           , 'white', ...
          'GridLineStyle'       , '-', ...
          'GridAlpha'           , 1, ...
          'Layer'               , 'top', ...
          'XAxisLocation'       , 'top', ...
          'XLim'                , [2.4, 6], ... % [3.7, 7]
          'XTick'               , 2:7, ...      % 4:7
          'XTickLabelRotation'  , 0, ...
          'XGrid'               , 'off', ...
          'XMinorGrid'          , 'off', ...
          'YLim'                , [0.1, 4.7], ...
          'YTick'               , []); hold on;
set(get(ax, 'YAxis') , 'Color'      , 'none')
set(get(ax, 'XLabel'), 'String'     , 'log_{10} cost [ATP/s]', ...
                       'Interpreter', 'tex', ...
                       'FontSize'   , 10, ...
                       'FontName'   , 'Arial')
% panel label
text('String'             , 'B', ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 12, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'centimeter', ...
     'Position'           , [-1.3, ax.Position(4) + 0.95], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;    

% plot total cost
xDat = 1 + [-0.2, 0.2];
yDat = log10([costDen.total, costSom.total]);
b = barh(xDat, yDat, ...
        'CData'    , [MediumDarkGrey; colors.LightGrey], ...
        'FaceColor', 'flat', ...
        'EdgeColor', 'none', ...
        'BarWidth' , 0.8); hold on;
set(get(b, 'BaseLine'), 'Color', 'none')

% plot transport cost if they are bigger than zero
xDat = 2 - 0.2;
yDat = log10(costDen.transp);
b    = barh(xDat, yDat, ...
               'CData'    , MediumDarkGrey, ...
               'FaceColor', 'none', ...
               'EdgeColor', 'flat', ...
               'BarWidth' , 0.35, ...
               'LineWidth', 0.75); hold on;
set(get(b, 'BaseLine'), 'Color', 'none')

% plot translation cost
xDat = 3 + [-0.2, 0.2];
yDat = log10([costDen.transl, costSom.transl]);
b = barh(xDat, yDat, ...
        'CData'    , [colors.DarkBlue; colors.LightBlue], ...
        'FaceColor', 'flat', ...
        'EdgeColor', 'none', ...
        'BarWidth' , 0.8); hold on;
set(get(b, 'BaseLine'), 'Color', 'none')

% plot transcription cost
xDat = 4 + [-0.2, 0.2];
yDat = log10([costDen.transcr, costSom.transcr]);
b = barh(xDat, yDat, ...
        'CData'    , [colors.DarkRed; colors.LightRed], ...
        'FaceColor', 'flat', ...
        'EdgeColor', 'none', ...
        'BarWidth' , 0.8); hold on;
set(get(b, 'BaseLine'), 'Color', 'none')

% manually set x-grid
plot([3, 3; 4, 4; 5, 5]', [ax.YLim; ax.YLim; ax.YLim]', ...
     'Color'    , 'white', ...
     'LineWidth', 0.5); hold on;

% label transcription cost bars with "som. mRNA" and "dendr. mRNA"
text('String'             , 'Dendr. mRNA', ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [ax.XLim(2), 4 - 0.2], ...
     'HorizontalAlignment', 'right', ...
     'VerticalAlignment'  , 'middle'); hold on;
text('String'             , 'Som. mRNA', ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [ax.XLim(2), 4 + 0.3], ...
     'HorizontalAlignment', 'right', ...
     'VerticalAlignment'  , 'middle'); hold on;

% label costs
for i = 1:4
    text('String'             , costLabels{i}, ...
         'Interpreter'        , 'tex', ...
         'FontSize'           , 10, ...
         'FontName'           , 'Arial', ...
         'Units'              , 'data', ...
         'Position'           , [ax.XLim(1), i], ...
         'HorizontalAlignment', 'right', ...
         'VerticalAlignment'  , 'middle'); hold on;
end

%% plot arrow from dendritic to somatic total cost and label with relative saving

% coordinates for arrow
leftArrowEnd  = -2.4*log10(costSom.total) + 3.4*log10(costDen.total);
rightArrowEnd =  0.8*log10(costSom.total) + 0.2*log10(costDen.total);
arrowX        = [leftArrowEnd, leftArrowEnd, rightArrowEnd, rightArrowEnd];
arrowY        = [0.5, 0.3, 0.3, 1];
% label with relative saving
relCostSaving = (costSom.total - costDen.total)/costSom.total*100;
arrowLabel    = ['-', num2str(round(relCostSaving)), '%'];
% plot arrow
plot(arrowX, arrowY, ...
     'Color'    , 'black', ...
     'LineWidth', 0.5); hold on;
scatter(leftArrowEnd, 0.5, ...
        'SizeData', 10, ...
        'Marker', '^', ...
        'MarkerEdgeColor', 'none', ...
        'MarkerFaceColor', 'black')
% label arrow
text('String'             , arrowLabel, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [0.5*leftArrowEnd + 0.5*rightArrowEnd, 0.3], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'top'); hold on;
