function plot_experimentalAbundancesVsNeuriteEnrichment(somata_m, neuropil_m, nStars_m, yLim_m, somata_p, neuropil_p, nStars_p, yLim_p)

% set panel labels
panelLabel = {'D'};

% initialise figure
figure('FileName', [char(datetime('today', 'Format', 'yyyy_MM_dd')), '_abundancesVsNeuriteEnrichment'], ...
       'Name'    , 'abundancesVsNeuriteEnrichment', ...
       'Units'   , 'centimeter', ...
       'Position', [2, 2, 6, 10]);

% load colors
load('3Reds4Blues4Greens3Greys3Violets.mat');

%% plot mRNA abundance 

% axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [1.25, 0.25, 1.5, 3], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'FontSize'            , 10, ...
          'FontName'            , 'Arial', ...
          'LineWidth'           , 0.5, ...
          'TickDir'             , 'out', ...
          'TickLength'          , [0.02, 0.02], ...
          'TickLabelInterpreter', 'tex', ...
          'XLim'                , [0.4, 2.6], ...
          'YLim'                , yLim_m); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YLabel'), 'String'     , 'log_{10} mRNA quant.', ...
                        'Interpreter', 'tex', ...
                        'FontSize'   , 10, ...
                        'FontName'   , 'Arial')
% panel label
text('String'             , panelLabel{1}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 12, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'centimeter', ...
     'Position'           , [-1, ax.Position(4) + 1.5], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;
% boxplot with mRNA abundance for "somata-enriched" mRNA
yDat = log10(2.^somata_m);
xDat = ones(size(yDat));
boxchart(xDat, yDat, ...
         'BoxWidth'        , 0.7, ...
         'MarkerStyle'     , 'none', ...
         'WhiskerLineColor', colors.Red, ...
         'BoxFaceColor'    , colors.Red, ...
         'BoxFaceAlpha'    , 0, ...
         'LineWidth'       , 1); hold on;
% boxplot with protein abundance for "neurite-enriched" mRNA with
% median in white on top
yDat = log10(2.^neuropil_m);
xDat = 2.*ones(size(yDat));
b    = boxchart(xDat, yDat, ...
                'BoxWidth'        , 0.7, ...
                'MarkerStyle'     , 'none', ...
                'WhiskerLineColor', colors.Red, ...
                'BoxFaceColor'    , colors.Red, ...
                'BoxFaceAlpha'    , 1, ...
                'LineWidth'       , 1); hold on;
xDat = 2 + (b.BoxWidth/2).*[-1, 1];
plot(xDat, median(yDat).*[1, 1], ...
     'Color', 'white', ...
     'LineWidth', 0.75); hold on;

%% significance bar for mRNA abundance

% create sub-axis
mat = [20,  0,  0,  0;
        0, 20,  0,  0;
        0,  0, 20,  0;
        0, 20,  0,  0]./20;
axes('Units'               , 'centimeter', ...
     'Position'            , ax.Position*mat + [0, 0, 0, 0.3], ...
     'Color'               , 'none', ...
     'Box'                 , 'off', ...
     'XLim'                , ax.XLim, ...
     'YLim'                , [0, 1]); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YAxis'), 'Color', 'none')
% significance bar
xDat = [1, 2];
yDat = [0.25, 0.25];
plot(xDat, yDat, ...
     'Color', 'black', ...
     'LineWidth', 0.5); hold on;
% show significance
if nStars_m > 0
    txt = repmat('\ast', 1, nStars_m);
else
    txt = 'ns';
end
text('String'             , txt, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [1.5, 0.25], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;

%% plot protein abundance

% axis
ax = axes('Units'               , 'centimeter', ...
          'Position'            , [4.25, 0.25, 1.5, 3], ...
          'Color'               , 'none', ...
          'Box'                 , 'off', ...
          'FontSize'            , 10, ...
          'FontName'            , 'Arial', ...
          'LineWidth'           , 0.5, ...
          'TickDir'             , 'out', ...
          'TickLength'          , [0.02, 0.02], ...
          'TickLabelInterpreter', 'tex', ...
          'XLim'                , [0.4, 2.6], ...
          'YLim'                , yLim_p, ...
          'YTick'               , ceil(yLim_p(1)):2:floor(yLim_p(2))); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YLabel'), 'String'     , 'log_{10} protein quant.', ...
                        'Interpreter', 'tex', ...
                        'FontSize'   , 10, ...
                        'FontName'   , 'Arial')
% boxplot with protein abundance for "somata-enriched" mRNA
yDat = log10(2.^somata_p);
xDat = ones(size(yDat));
boxchart(xDat, yDat, ...
         'BoxWidth'        , 0.7, ...
         'MarkerStyle'     , 'none', ...
         'WhiskerLineColor', colors.Blue, ...
         'BoxFaceColor'    , colors.Blue, ...
         'BoxFaceAlpha'    , 0, ...
         'LineWidth'       , 1); hold on;
% boxplot with protein abundance for "neurite-enriched" mRNA with
% median in white on top
yDat = log10(2.^neuropil_p);
xDat = 2.*ones(size(yDat));
b    = boxchart(xDat, yDat, ...
                'BoxWidth'        , 0.7, ...
                'MarkerStyle'     , 'none', ...
                'WhiskerLineColor', colors.Blue, ...
                'BoxFaceColor'    , colors.Blue, ...
                'BoxFaceAlpha'    , 1, ...
                'LineWidth'       , 1); hold on;
xDat = 2 + (b.BoxWidth/2).*[-1, 1];
plot(xDat, median(yDat).*[1, 1], ...
     'Color', 'white', ...
     'LineWidth', 0.75); hold on;

%% significance bar for protein abundance

% axis
mat = [20,  0,  0,  0;
        0, 20,  0,  0;
        0,  0, 20,  0;
        0, 20,  0,  0]./20;
axes('Units'               , 'centimeter', ...
     'Position'            , ax.Position*mat + [0, 0, 0, 0.3], ...
     'Color'               , 'none', ...
     'Box'                 , 'off', ...
     'XLim'                , ax.XLim, ...
     'YLim'                , [0, 1]); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YAxis'), 'Color', 'none')
% significance bar
xDat = [1, 2];
yDat = [0.25, 0.25];
plot(xDat, yDat, ...
     'Color', 'black', ...
     'LineWidth', 0.5); hold on;
% show significance
if nStars_p > 0
    txt = repmat('\ast', 1, nStars_p);
else
    txt = 'ns';
end
text('String'             , txt, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [1.5, 0.25], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'bottom'); hold on;

%% legend

% axis
axes('Units'               , 'centimeter', ...
     'Position'            , [0.25, 3.7, 5.25, 0.75], ...
     'Color'               , 'none', ...
     'Box'                 , 'off', ...
     'XLim'                , [0, 1], ...
     'YLim'                , [0, 1]); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YAxis'), 'Color', 'none')
% mock data for markers
yDat = 0.7.*rand(1, 500) + 0.1;
% colors.Red marker for "somata-enriched mRNA"
xDat = 0.06.*ones(size(yDat));
boxchart(xDat, yDat, ...
         'BoxWidth'        , 0.03, ...
         'MarkerStyle'     , 'none', ...
         'WhiskerLineColor', colors.Red, ...
         'BoxFaceColor'    , colors.Red, ...
         'BoxFaceAlpha'    , 0, ...
         'LineWidth'       , 1); hold on;
% colors.Blue marker for "somata-enriched mRNA"
xDat = 0.1.*ones(size(yDat));
boxchart(xDat, yDat, ...
         'BoxWidth'        , 0.03, ...
         'MarkerStyle'     , 'none', ...
         'WhiskerLineColor', colors.Blue, ...
         'BoxFaceColor'    , colors.Blue, ...
         'BoxFaceAlpha'    , 0, ...
         'LineWidth'       , 1); hold on;
% label for "somata-enriched mRNA"
text('String'             , {'Somata-enriched', 'mRNAs'}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 7, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [0.13, 0.5], ...
     'HorizontalAlignment', 'left', ...
     'VerticalAlignment'  , 'middle'); hold on;
% colors.Red marker for "neurite-enriched mRNA" with median in white on top
xDat = 0.58.*ones(size(yDat));
b    = boxchart(xDat, yDat, ...
                'BoxWidth'        , 0.03, ...
                'MarkerStyle'     , 'none', ...
                'WhiskerLineColor', colors.Red, ...
                'BoxFaceColor'    , colors.Red, ...
                'BoxFaceAlpha'    , 1, ...
                'LineWidth'       , 1); hold on;
xDat = 0.58 + (b.BoxWidth/2).*[-1, 1];
plot(xDat, median(yDat).*[1, 1], ...
     'Color', 'white', ...
     'LineWidth', 0.75); hold on;
% colors.Blue marker for "neurite-enriched mRNA" with median in white on top
xDat = 0.62.*ones(size(yDat));
b    = boxchart(xDat, yDat, ...
                'BoxWidth'        , 0.03, ...
                'MarkerStyle'     , 'none', ...
                'WhiskerLineColor', colors.Blue, ...
                'BoxFaceColor'    , colors.Blue, ...
                'BoxFaceAlpha'    , 1, ...
                'LineWidth'       , 1); hold on;
xDat = 0.62 + (b.BoxWidth/2).*[-1, 1];
plot(xDat, median(yDat).*[1, 1], ...
     'Color', 'white', ...
     'LineWidth', 0.75); hold on;
% label for "neurite-enriched mRNA"
text('String'             , {'Neurite-enriched', 'mRNAs'}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 7, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'data', ...
     'Position'           , [0.65, 0.5], ...
     'HorizontalAlignment', 'left', ...
     'VerticalAlignment'  , 'middle'); hold on;

%% panel label "Data from Zappulo et al., 2017"

% axis
axes('Units'               , 'centimeter', ...
     'Position'            , [0.5, 4.4, 5.25, 0.5], ...
     'Color'               , 'none', ...
     'Box'                 , 'off', ...
     'XLim'                , [0, 1], ...
     'YLim'                , [0, 1]); hold on;
set(get(gca, 'XAxis'), 'Color', 'none')
set(get(gca, 'YAxis'), 'Color', 'none')
% label 
text('String'             , {'Data rep. in Zappulo et al., 2017'}, ...
     'Interpreter'        , 'tex', ...
     'FontSize'           , 10, ...
     'FontName'           , 'Arial', ...
     'Units'              , 'normalized', ...
     'Position'           , [0.5, 0.8], ...
     'HorizontalAlignment', 'center', ...
     'VerticalAlignment'  , 'middle'); hold on;    
